const Item = require("./class/Item")
const Drinks= require("./class/Item")
const DrinksCream= require("./class/Item")

export const coffeeHot = [
    new Drinks("아메리카노", 3000, "/static/picture/americano.png",true)
    , new Drinks("유자차", 4500, "/static/picture/tea.png", true)
    , new Drinks("아메카노", 3000, "/static/picture/americano.png", true)
    , new Drinks("유자차", 4500, "/static/picture/tea.png", true)
    , new Drinks("아메리노", 3000, "/static/picture/americano.png", true)
    , new Drinks("유자차", 4500, "/static/picture/tea.png", true)
    , new Drinks("아리카노", 3000, "/static/picture/americano.png", true)
    , new Drinks("유자차", 4500, "/static/picture/tea.png", true)
    , new Drinks("아메리카노", 3000, "/static/picture/americano.png", true)
    , new Drinks("유자차", 4500, "/static/picture/tea.png", true)
    , new Drinks("아메리카노", 3000, "/static/picture/americano.png", true)
    , new Drinks("유자차", 4500, "/static/picture/tea.png", true)
    , new Drinks("아메리카노", 3000, "/static/picture/americano.png", true)
    , new Drinks("유자차", 4500, "/static/picture/tea.png", true)
    , new Drinks("아메리카노", 3000, "/static/picture/americano.png", true)
];

export const coffeeIce = [
    new Drinks("아메리카노", 3000, "/static/picture/americano.png")
    , new Drinks("유자차", 4500, "/static/picture/tea.png")
    , new Drinks("아메카노", 3000, "/static/picture/americano.png")
    , new Drinks("유자차", 4500, "/static/picture/tea.png")
    , new Drinks("아메리노", 3000, "/static/picture/americano.png")
    , new Drinks("유자차", 4500, "/static/picture/tea.png")
    , new Drinks("아리카노", 3000, "/static/picture/americano.png")
    , new Drinks("유자차", 4500, "/static/picture/tea.png")
    , new Drinks("아메리카노", 3000, "/static/picture/americano.png")
    , new Drinks("유자차", 4500, "/static/picture/tea.png")
    , new Drinks("아메리카노", 3000, "/static/picture/americano.png")
    , new Drinks("유자차", 4500, "/static/picture/tea.png")
    , new Drinks("아메리카노", 3000, "/static/picture/americano.png")
    , new Drinks("유자차", 4500, "/static/picture/tea.png")
    , new Drinks("아메리카노", 3000, "/static/picture/americano.png")
];
